version: '3'

services:
  app:
    image: bambustudio:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/fuse:/dev/fuse
    cap-add:
      - SYS_ADMIN
    network_mode: host

    # Setting privileged true will allow UI to come up. Still some brokenness though.
    #
    # Make sure on the host side you allow xhost local connections:
    #   $ xhost +Local:
    #   $ xhost
    #
    # Fuse may need to have permission to use the allow_other option when not root. Turn this on in
    # /etc/fuse.conf on the host:
    #   user_allow_other
    # It was also recommended to bind-mount /etc/fuse.conf to /etc/fuse.conf in the container...
    # Those didn't seem to fix the issue - at least on their own.
    #
    # SELinux policy exclusions needed as well, on the host side:
    #   # ausearch -c 'bambustu_main' --raw | audit2allow -M my-bambustumain
    #   # semodule -i my-bambustumain.pp
    #security_opt:
    #  - seccomp:unconfined

    # Keep investigating what perms are needed to avoid using the below `privileged: true`.
    privileged: true
